#!/bin/bash
# Quick Start Guide for VJ System

echo "==================================="
echo "  VJ System - Quick Start Guide"
echo "==================================="
echo ""
echo "✅ CORRECT WAY TO START:"
echo "   ./start.sh"
echo ""
echo "   This will:"
echo "   - Use venv Python ✅"
echo "   - Start backend on port 8765 ✅"
echo "   - Start frontend on port 8000 ✅"
echo "   - Auto-open browser ✅"
echo ""
echo "🌐 BROWSER URL:"
echo "   http://localhost:8000/visualdmx.html"
echo ""
echo "🛑 TO STOP:"
echo "   Press Ctrl+C in the terminal"
echo ""
echo "==================================="
echo "  What's Running:"
echo "==================================="
echo ""
echo "Backend (Python):"
echo "  - DMX Engine with Smart Logic"
echo "  - Animation Engine (laser coordination)"
echo "  - Shape Intelligence (28 shapes)"
echo "  - Precise Audio Analysis ✅"
echo "  - WebSocket Server (port 8765)"
echo ""
echo "Frontend (Browser):"
echo "  - visualdmx.html UI"
echo "  - HTTP Server (port 8000)"
echo ""
echo "==================================="
echo "  System Status:"
echo "==================================="
echo ""
echo "✅ Laser zones paired: 'laser' (Left + Right)"
echo "✅ Audio: Processing Active"
echo "✅ DMX: Connected to /dev/ttyUSB0"
echo "✅ Audio: System monitor routing"
echo ""
echo "==================================="
